Granular configuration of auto-endorsement
hyperledger/aries-endorser-service pull request #34
Opened 2023-09-28 00:40 UTC by Gavinok

This pull request resolves #32

The endorser service supports auto-endorsing specific types of transaction, however it is not designed to support more fine-grained control mechanisms.

Here we add a new `/allow/` endpoint which can add to, delete from, and get a list of transactions which will be auto-endorsed. There is a list for:
- publishing DIDs
- publishing schema definitions
- publishing credential definitions

When any of these lists are updated all pending transactions will be compared and if a match between one of these lists and the pending transactions is found the transaction will be endorsed.

![2023-09-27_16-39-56](https://github.com/hyperledger/aries-endorser-service/assets/34443260/871415b1-ac51-4758-9abc-d19c61b46dd5)

In addition, a new configuration setting `ENDORSER_REJECT_BY_DEFAULT` has been introduced to control whether transactions that do not match any of the allow lists are rejected, or left pending by default

Currently remaining work to be done:
- [ ] Document how the new allow lists work
- [ ] Integrate RevRegEntry and RevRegDef entries in the creddef configuration
- [ ] Add integration and unit tests

2023-10-11 21:12 UTC, esune requested changes
Just a couple of small comments/tweaks, looking great otherwise!

2023-10-13 17:47 UTC, esune requested changes
Final tweak, remaining changes look good to me

2023-10-13 17:47 UTC, esune commented on endorser/api/db/models/allow.py
>      # TODO change to boolean
Remove the TODO now? 🙂

2023-10-13 17:49 UTC, esune commented on endorser/api/db/models/allow.py
> +from sqlalchemy.dialects.postgresql import UUID, TIMESTAMP
If it is broadly used in the project we may as well leave it, I didn't realize it was already being used elsewhere and thought it was a new addition.

2023-10-13 17:53 UTC, Gavinok commented on endorser/api/db/models/allow.py
>      # TODO change to boolean
How did I miss this 💀

2023-10-13 18:12 UTC, esune approved these changes
Looks good to me! 👍🏻

2023-10-13 19:54 UTC, swcurran approved these changes
Approved based on @esune ’s review.

2023-10-13 19:54 UTC, merged